<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wartergen.App\Wartergen.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Wartergen.Wc3Terrain.Tests\TestData\terrain.json" Link="TestData\terrain.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Wartergen.Wc3Terrain.Tests\TestData\war3map.w3e" Link="TestData\war3map.w3e" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
